#!/bin/sh

export JAVA_HOME=/usr/lib/jvm/java-1.7.0

CLASSPATH=${CLASSPATH}:$JAVA_HOME/lib/tools.jar

export PATH=/usr/local/cuda/bin:$PATH
LD_LIBRARY_PATH=/var/caffe/distribute/lib:/var/caffe/distribute/python:/usr/local/lib:/usr/lib64:/jre/lib/amd64:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.1.el7_1.x86_64/jre/lib/amd64/server:/usr/local/lib:/usr/local/lib64:/usr/local/cuda/lib64
export LD_LIBRARY_PATH=/usr/local/lib:/opt/anaconda/lib:$JAVA_HOME/jre/lib/amd64:$JAVA_HOME/jre/lib/amd64/server:$LD_LIBRARY_PATH
cd $(dirname $BASH_SOURCE)
/opt/anaconda/bin/python zedge_classifier.py 1>>/var/log/zedge_convnet2/web.stderr 2>&1 &

